# Generated by Django 2.1.3 on 2018-12-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_number', models.IntegerField(db_index=True, help_text='CAD event number')),
                ('call_clearance_description', models.CharField(blank=True, max_length=100, null=True)),
                ('method_call_received', models.CharField(blank=True, max_length=80, null=True)),
                ('call_priority', models.IntegerField(default=0)),
                ('initial_call_type', models.CharField(blank=True, max_length=120, null=True)),
                ('final_call_type', models.CharField(blank=True, max_length=120, null=True)),
                ('time_queued', models.DateTimeField(blank=True, null=True)),
                ('first_officer_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('precinct', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=20, null=True)),
                ('beat', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'ordering': ('-time_queued',),
            },
        ),
    ]
