# Generated by Django 2.1.3 on 2018-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='first_officer_arrival_time',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='time_queued',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
