# Generated by Django 2.1.3 on 2018-12-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting', '0002_auto_20181201_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='first_officer_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='time_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
