# Generated by Django 2.1.3 on 2018-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting', '0003_auto_20181201_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_sexual_assault',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
