# Generated by Django 2.1.3 on 2018-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting', '0004_call_is_sexual_assault'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_rape',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
